stages:
  - test
  - sonarqube

variables:
  CHROME_BIN: /usr/bin/chromium
  NODE_OPTIONS: "--max_old_space_size=4096"

cache:
  paths:
    - node_modules/
  key: 
    files:
      - package-lock.json

test:
  stage: test
  image: node:18
  before_script:
    - apt-get update && apt-get install -y chromium
    # Remove lock file to avoid sync issues
    - rm -f package-lock.json
    - npm install
    - npm install karma-sonarqube-unit-reporter --save-dev
    # Ensure reports directory exists
    - mkdir -p reports
  script:
    - npm run test-headless -- --code-coverage
  artifacts:
    paths:
      - coverage/
      - reports/
    expire_in: 1 week
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura.xml
  coverage: '/Lines.*?(\d+(?:\.\d+)?)%/'

sonarqube:
  stage: sonarqube
  image: sonarsource/sonar-scanner-cli:latest
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner -Dsonar.projectVersion=${CI_COMMIT_SHORT_SHA}
  dependencies:
    - test
