name: Angular CI
on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]  # Match your GitLab CI setup
        
    steps:
    - uses: actions/checkout@v4  # Updated to v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4  # Updated to v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'package-lock.json'  # Explicit cache path
        
    # Fallback cache setup in case setup-node cache fails
    - name: Cache node modules
      uses: actions/cache@v4
      if: failure()  # Only run if previous step fails
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
          
    - name: Install Dependencies
      run: npm ci --prefer-offline --no-audit
      
    - name: Build
      run: npm run build --if-present -- --configuration production
      
    - name: Lint
      run: npm run lint
      
    - name: Test
      run: npm run test-headless -- --code-coverage
      
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4  # Updated to v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        
    - name: Upload test results to Codecov
      if: ${{ !cancelled() }}
      uses: codecov/test-results-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
